import mongoose, { Schema } from 'mongoose'
import { ICMIApiLogs } from '../models/CMIApiLogsModel'

const CMIApiLogsSchema: Schema = new Schema(
  {
    itemID: { type: String, required: true, unique: true }, // uuid
    refNo: { type: String, required: true },
    apiName: { type: String, required: true },
    headerStatus: { type: String, required: true },
    requestDate: { type: Date, required: true },
    request: { type: String, required: true },
    name: { type: String, required: true },
    lastName: { type: String, required: true },
    tel: { type: String, required: true },
    email: { type: String, required: true },
    channel: { type: String, required: true },
    orderNo: { type: String, required: true },
    orderStatus: { type: String, required: true },
    paymentNo: { type: String, required: true },
    licensePlate: { type: String, required: true },
    insOrderNo: { type: String, required: true },
    message: { type: String, required: true },
    responseDate: { type: Date, required: true },
    response: { type: String, required: true },
    remark: { type: String, required: true },
    createdBy: { type: String, required: true },
    updatedBy: { type: String, required: true },
    detail: {
      chassisNo: { type: String, required: false },
      carType: { type: String, required: false },
      carBrandName: { type: String, required: false },
      carModelName: { type: String, required: false },
      provinceName: { type: String, required: false },
      effectiveDate: { type: Date, required: false },
      expiredDate: { type: Date, required: false },
      techMessage: { type: String, required: false },
      paymentDate: { type: Date, required: false },
      paymentChannel: { type: String, required: false },
      paymentStatus: { type: String, required: false },
      paymentMessage: { type: String, required: false },
      paymentResultDate: { type: Date, required: false },
      paymentResultStatus: { type: String, required: false },
      paymentNo: { type: String, required: false },
      amount: { type: Number, required: false },
      policyResultDate: { type: Date, required: false },
      policyNo: { type: String, required: false },
      covernote: { type: String, required: false },
      partnerCode: { type: String, required: false },
      partnerRefNo: { type: String, required: false },
      insOrderNo: { type: String, required: false },
      crossRunningNo: { type: String, required: false },
      runningNo: { type: String, required: false },
      documentResultDate: { type: Date, required: false },
      documentNo: { type: String, required: false },
      transactionNo: { type: String, required: false },
      fileAttatchmentNo: { type: String, required: false },
      fileAttatchmentCode: { type: String, required: false },
      fileAttatchmentName: { type: String, required: false },
      fileIndex: { type: String, required: false },
    },
  },
  {
    timestamps: true,
    collection: 'CMIApiLogs',
  },
)

export const CMIApiLogsEntity =
  mongoose.models.CMIApiLogs || mongoose.model<ICMIApiLogs>('CMIApiLogs', CMIApiLogsSchema)
